version: '3.7'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    # env_file:
      # - .env.dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  adminer:
    image: adminer
    ports: 
      - 8080:8080
volumes:
  pgdata: